# Generated by Django 4.2.4 on 2023-08-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField(help_text="Borrow date")),
                (
                    "expected_return_date",
                    models.DateField(
                        help_text="Expected return date (value should be greater or equal then borrow_date)"
                    ),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual retutn date (value should be greater or equal then borrow_date)",
                        null=True,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="ID of borrowed book",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowings",
                        to="book.book",
                    ),
                ),
            ],
        ),
    ]
