# Generated by Django 4.2.4 on 2023-08-30 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the book", max_length=255),
                ),
                (
                    "author",
                    models.CharField(help_text="Author of the book", max_length=255),
                ),
                (
                    "cover",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Hard"), (2, "Soft")],
                        help_text="Cover of the book",
                    ),
                ),
                (
                    "inventory",
                    models.PositiveIntegerField(
                        help_text="Copies of the book available for borrowing (positive)",
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ],
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of daily fee when book is borrowed (positive)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ],
                    ),
                ),
            ],
        ),
    ]
